spring: 
  project: 
    env: mysql
  datasource: 
    url: jdbc:mysql://localhost:3306/
    username: root
    password: jasper840831
    driver-class-name: com.mysql.jdbc.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    

  thymeleaf: 
    cache: false
    prefix: classpath:/templates/    # 設定去templates資料夾找html檔案
    suffix: .html
    encoding: UTF-8
    mode: HTML5