spring: 
#  profiles: 
#    active: mysql
   profiles: 
    active: postgresql
    
   thymeleaf: 
    cache: false
    prefix: classpath:/templates/    # 設定去templates資料夾找html檔案
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    
logging:
  config: classpath:log4j2.yml
       
#server: 
#  port: 80
server:
  port : 5000 # aws啟動端口號